[package]
name = "prism-modular-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "=0.28.0"
glam = "0.25.0"
prism-renderer = {path = "prism-renderer"}