[package]
name = "vk-context"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.61"
ash = "0.38"
ash-window = "0.13.0"
raw-window-handle = "0.6.2"
gpu-allocator = {git = "https://github.com/Traverse-Research/gpu-allocator.git", branch = "ash-0.38"}
