[package]
name = "pbr-render-pass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mesh-structs = {path = "../common/mesh-structs"}
camera-3d = {path = "../common/camera-3d"}
image = "0.25.1"
